### ISSUE TITLE
Problem with format string

### ISSUE THREAD

**Issue by uzyfeo** [amosnier/sha-2#1]
You have a little typo in your format string in test.c at line 184

This:
`printf("input starts with 0x%02x, length %lu\n", *input, input_len);`
...should be this:
`printf("input starts with 0x%02x, length %zu\n", *input, input_len);`

Although z switch is C99 addition....

Problem lies in that that you assume that size_t is long unsigned but it is indeed whatever compilers treats it as.
z switch can be used to tell compiler input is of type size_t which is the right way to do.

You can do the same with compile time check if you want to be pre-C99 conformant but this should definitely be fixed, as it is undefined behavior and could cause memory leak.

**Comment by uzyfeo** [comment]
Also, I couldn't compile for some time... Took me a few minutes to realize that line 44 in test.c with define
`#define LARGE_MESSAGES 1`
won't really work on Windows with its 1mb stack limit... After changing it to 0, everything compiled as it should.

It should be noted somewhere in ReadMe or made compile-time specific for Windows (don't allow it at all or something).

**Comment by amosnier** [comment]
The comment about large messages has nothing to do with this issue. Could you please make that a separate issue.
Thanks.

**Comment by amosnier** [comment]
Thanks a lot for reporting this.
I hardly see how it could cause a memory leak, but I can easily imagine a bus error (is size_t is too small), or printing garbage (if size_t is too large).
Note that since I do want ANSI C-compatibility, and since the actual test array sizes that are less than ULONG_MAX, I just use an explicit cast to solve the problem.
I am happy that you like the implementation. Thanks.
I will now close the issue.
