### ISSUE TITLE
Why include the .h in the repo?

### ISSUE THREAD

**Issue by mcp292** [amosnier/sha-2#5]
I found your implementation and goals [here](https://codereview.stackexchange.com/questions/182812/self-contained-sha-256-implementation-in-c). This is exactly what I was looking for! Something like [Keccak standalone files](https://github.com/XKCP/XKCP/tree/master/Standalone) where you only have to include the [`.c`](https://github.com/XKCP/XKCP/blob/master/Standalone/CompactFIPS202/C/Keccak-readable-and-compact.c) and don't even have to edit your `makefile`. I guess I could do the same with yours so the question is: why include the `.h` in the repo?

**Comment by amosnier** [comment]
@mcp292, I'm not sure I understand what you mean. Do you mean include as in `#include "sha-256.c"`? While that will work if you only do that in one of your C-files, that will create conflicting multiple definitions as soon as you do that more than once in a set of files that are linked together.
Having the declaration in a header file which is included in the implementation file lets the compiler check that the declaration is correct, which in it's turn makes the header file safe to include in the other files that want to invoke the function(s) it declares, without creating multiple conflicting definitions.
In my experience, that way of structuring a C-module is standard.
More simply, the answer to your question "why include the .h in the repo?" is: because I use it.

**Comment by mcp292** [comment]
Got it.
